version: '2'
 
services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    restart: always
   
  influxdb:
    image: influxdb
    container_name: influxdb
    restart: always
    environment:
     - INFLUXDB_DB="iot"
     - INFLUXDB_USER="gatherer"
     - INFLUXDB_USER_PASSWORD="password"
    volumes:
     - ./influxdb:/var/lib/influxdb
 
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
     - "3000:3000"
    volumes:
      - grafana-db:/var/lib/grafana
      - grafana-log:/var/log/grafana
      - grafana-conf:/etc/grafana

  bridge:
    image: mqtt-influx-bridge
    container_name: bridge
    restart: always

volumes:
  grafana-db:
    driver: local  
  grafana-log:
    driver: local
  grafana-conf:
    driver: local
