version: '2'
 
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
    expose:
      - 9090
    links:
      - cadvisor:cadvisor
      - node-exporter:node-exporter
      - mosquitto-exporter:mosquitto-exporter
  
  mosquitto-exporter:
    image: sapcc/mosquitto-exporter:0.6.0
    restart: always
    container_name: mosquitto-exporter
    environment:
      - BROKER_ENDPOINT=tcp://mosquitto:1883
 
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - "9001:9001"
      - "1883:1883"
    restart: always
   
  influxdb:
    image: influxdb
    container_name: influxdb
    restart: always
    environment:
     - INFLUXDB_DB="iot"
     - INFLUXDB_USER="gatherer"
     - INFLUXDB_USER_PASSWORD="password"
    volumes:
     - ./influxdb:/var/lib/influxdb
 
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
     - "3000:3000"
    volumes:
      - grafana-db:/var/lib/grafana
      - grafana-log:/var/log/grafana
      - grafana-conf:/etc/grafana

  bridge:
    image: mqtt-influx-bridge
    container_name: bridge
    restart: always
    environment:
      - QOS:1

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    expose:
      - 9100

  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    restart: unless-stopped
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    expose:
      - 8080

volumes:
  grafana-db:
    driver: local  
  grafana-log:
    driver: local
  grafana-conf:
    driver: local
