datasources:
- name: InfluxDB
  type: influxdb
  access: proxy
  database: iot
  user: gatherer
  url: http://influxdb:8086
  is_default: true
  # <int> org id. will default to orgId 1 if not specified
  orgId: 1
  # <string> database password, if used
  password: "password"
  # <string> database user, if used
  user: "gatherer"
  # <string> database name, if used
  database: "iot"
  # <bool> enable/disable basic auth
  basicAuth: false
  # <string> basic auth username
  basicAuthUser: 
  # <string> basic auth password
  basicAuthPassword: 
  # <bool> enable/disable with credentials headers
  withCredentials: false
  # <bool> mark as default datasource. Max one per org
  isDefault:	false
  # <map> fields that will be converted to json and stored in json_data
  jsonData:
     graphiteVersion: "1.1"
     tlsAuth: false
     tlsAuthWithCACert: false
  # <string> json object of data that will be encrypted.
  secureJsonData:
    password: password
    tlsCACert: ""
    tlsClientCert: ""
    tlsClientKey: ""
  version: 1
  # <bool> allow users to edit datasources from the UI.
  editable: true
